version: '3'
services:
  # there is a bug and docker is not spawning yarn dev not accessible through the network
  # web:
  #   build: web/
  #   entrypoint: /bin/sh -c "yarn && yarn dev"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./web/src:/app/src/:ro
  #   depends_on:
  #     - api
  #   networks:
  #     - web
  #     - api

  api:
    build: api/
    volumes:
      - ./api/src:/app/src/:ro
      - config:/app/config/:rw
      - uploads:/app/uploads
    ports:
     - "3001:3001"
    depends_on:
      - db
    networks:
      - api
      - db

  db:
    image: postgis/postgis:13-master
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - env.db
    volumes:
      - db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db

networks:
  web:
    external: true
  api:
  db:


volumes:
  db:
  uploads:
  config: